---
- hosts: us,usca,au
  remote_user: root
  become: yes 
  tasks:
  - name: git pull
    git:
      repo: git@gitlab.com:hanglihl/modesens-frontend.git
      dest: /modesens/modesens-frontend/
      version: master
      update: yes
      accept_hostkey: yes
      force: yes
    register: result
  - debug: msg="{{result.before}}->{{result.after}}"

  - name: clean nuxt scripts.
    command: "/bin/rm -rf /modesens/modesens-frontend/modesens/.nuxt/*"
    args:
      warn: no

  - name: install packages.
    command: "npm install"

  - name: get nuxt server scripts from s3.
    command: "aws s3 sync s3://modesens/nuxt /modesens/modesens-frontend/modesens/.nuxt --delete --cache-control max-age=0"

  - name: pm2 restart.
    command: "pm2 startOrReload server.json"
    args:
      chdir: /modesens/modesens-frontend/modesens



